/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Makes an HTTP request using rquest.
 *
 * - `session`: A unique string ID for the client session. Clients are re-used if the same session is provided.
 * - `method`: HTTP method (e.g. "GET", "POST", "PUT", "DELETE").
 * - `url`: The URL to which the request is sent.
 * - `headers`: A stringified JSON object of the form Record<string, string>.
 * - `body`: The request body. An empty string means no body.
 *
 * The response is returned as a stringified JSON of the form:
 * { "status": number, "headers": Record<string, string[]>, "body": string }.
 */
export declare function request(session: string, method: string, url: string, headers: string, body: string, timeoutMs: number): Promise<string>
/**
 * Releases a session by removing its associated client.
 * If the session does not exist, nothing happens.
 */
export declare function freeSession(session: string): void
/** Returns the number of unique sessions in HashMap */
export declare function getSessionsCount(): number
